module.exports={
    configurewebpack:{
        resolve:{
            alias:{
                "assets":"@/assets",
                'common':'@/common',
                'network':'@/network',
                'components':'@/components',
                'views':'@/views'
            }
        }
    }
}